package main

import (
	"crypto/sha256"
	"fmt"
	"log"
	"os"
	"strings"
	"time"

	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// AppInfo holds application routing information
type AppInfo struct {
	Name       string
	Namespace  string
	Domain     string
	Port       int
	SSLEnabled bool
	Status     string
	ServiceIP  string
}

// reconcile is the main reconciliation loop
func (w *Watcher) reconcile() error {
	start := time.Now()

	// 1. Fetch apps from database
	appsFromDB, err := w.fetchAppsFromDB()
	if err != nil {
		return fmt.Errorf("failed to fetch apps from DB: %w", err)
	}

	log.Printf("📊 Found %d apps in database", len(appsFromDB))

	// 2. If using Kubernetes, enrich with k8s service info
	if w.k8sClient != nil {
		if err := w.enrichWithKubernetesInfo(appsFromDB); err != nil {
			log.Printf("⚠️  K8s enrichment failed: %v", err)
		}
	}

	// 3. Generate Traefik configuration
	config := w.generateTraefikConfig(appsFromDB)

	// 4. Calculate config hash
	configHash := w.calculateHash(config)

	// 5. Check if config changed
	if configHash == w.lastHash {
		log.Printf("✓ Config unchanged (hash: %s)", configHash[:8])
		return nil
	}

	// 6. Write config to file
	if err := w.writeConfig(config); err != nil {
		return fmt.Errorf("failed to write config: %w", err)
	}

	// 7. Update hash
	w.lastHash = configHash

	elapsed := time.Since(start)
	log.Printf("✅ Config updated successfully (hash: %s, elapsed: %v)", configHash[:8], elapsed)

	return nil
}

// fetchAppsFromDB queries database for deployed apps
func (w *Watcher) fetchAppsFromDB() ([]AppInfo, error) {
	query := `
		SELECT 
			d.app_name,
			COALESCE(d.port, 3000) as port,
			d.status,
			COALESCE(s.custom_domain, '') as custom_domain,
			COALESCE(s.ssl_enabled, false) as ssl_enabled
		FROM app_deployments d
		LEFT JOIN app_public_settings s ON d.app_name = s.app_name
		WHERE d.status = 'deployed'
		ORDER BY d.app_name
	`

	rows, err := w.db.Query(query)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var apps []AppInfo
	for rows.Next() {
		var app AppInfo
		if err := rows.Scan(&app.Name, &app.Port, &app.Status, &app.Domain, &app.SSLEnabled); err != nil {
			log.Printf("⚠️  Failed to scan row: %v", err)
			continue
		}

		// Set namespace for k8s mode
		if w.k8sClient != nil {
			app.Namespace = "citizen-app-" + app.Name
		}

		apps = append(apps, app)
	}

	return apps, rows.Err()
}

// enrichWithKubernetesInfo adds Kubernetes service information
func (w *Watcher) enrichWithKubernetesInfo(apps []AppInfo) error {
	for i := range apps {
		app := &apps[i]

		// Get service from Kubernetes
		svc, err := w.k8sClient.CoreV1().Services(app.Namespace).Get(
			metav1.Background(),
			app.Name,
			metav1.GetOptions{},
		)

		if err != nil {
			log.Printf("⚠️  Service not found for %s: %v", app.Name, err)
			continue
		}

		// Update with actual service IP
		app.ServiceIP = svc.Spec.ClusterIP

		// Use service port if available
		if len(svc.Spec.Ports) > 0 {
			app.Port = int(svc.Spec.Ports[0].Port)
		}

		log.Printf("🔍 Enriched %s: IP=%s, Port=%d", app.Name, app.ServiceIP, app.Port)
	}

	return nil
}

// generateTraefikConfig generates Traefik dynamic configuration YAML
func (w *Watcher) generateTraefikConfig(apps []AppInfo) string {
	var sb strings.Builder

	sb.WriteString("# Traefik Dynamic Configuration\n")
	sb.WriteString("# Generated by Citizen Traefik Watcher v2\n")
	sb.WriteString(fmt.Sprintf("# Generated at: %s\n", time.Now().Format(time.RFC3339)))
	sb.WriteString("# DO NOT EDIT MANUALLY - This file is auto-generated\n\n")

	sb.WriteString("http:\n")
	sb.WriteString("  routers:\n")

	// Generate routers
	for _, app := range apps {
		if app.Domain == "" {
			continue
		}

		routerName := fmt.Sprintf("citizen-%s", app.Name)
		serviceName := fmt.Sprintf("citizen-%s-service", app.Name)

		// HTTP router (redirect to HTTPS if SSL enabled)
		if app.SSLEnabled {
			sb.WriteString(fmt.Sprintf("    %s-http:\n", routerName))
			sb.WriteString(fmt.Sprintf("      rule: \"Host(`%s`)\"\n", app.Domain))
			sb.WriteString("      entryPoints:\n")
			sb.WriteString("        - web\n")
			sb.WriteString("      middlewares:\n")
			sb.WriteString("        - https-redirect\n")
			sb.WriteString("\n")
		}

		// HTTPS router
		sb.WriteString(fmt.Sprintf("    %s:\n", routerName))
		sb.WriteString(fmt.Sprintf("      rule: \"Host(`%s`)\"\n", app.Domain))
		sb.WriteString("      entryPoints:\n")

		if app.SSLEnabled {
			sb.WriteString("        - websecure\n")
			sb.WriteString("      tls:\n")
			sb.WriteString("        certResolver: letsencrypt\n")
		} else {
			sb.WriteString("        - web\n")
		}

		sb.WriteString(fmt.Sprintf("      service: %s\n", serviceName))
		sb.WriteString("\n")
	}

	sb.WriteString("  services:\n")

	// Generate services
	for _, app := range apps {
		if app.Domain == "" {
			continue
		}

		serviceName := fmt.Sprintf("citizen-%s-service", app.Name)

		sb.WriteString(fmt.Sprintf("    %s:\n", serviceName))
		sb.WriteString("      loadBalancer:\n")
		sb.WriteString("        servers:\n")

		// Use Service ClusterIP if available (k8s mode)
		if app.ServiceIP != "" {
			sb.WriteString(fmt.Sprintf("          - url: \"http://%s:%d\"\n", app.ServiceIP, app.Port))
		} else {
			// Fallback to container name (docker mode)
			sb.WriteString(fmt.Sprintf("          - url: \"http://%s:%d\"\n", app.Name, app.Port))
		}

		sb.WriteString("\n")
	}

	// Add middlewares
	sb.WriteString("  middlewares:\n")
	sb.WriteString("    https-redirect:\n")
	sb.WriteString("      redirectScheme:\n")
	sb.WriteString("        scheme: https\n")
	sb.WriteString("        permanent: true\n")

	return sb.String()
}

// calculateHash calculates SHA256 hash of config
func (w *Watcher) calculateHash(config string) string {
	hash := sha256.Sum256([]byte(config))
	return fmt.Sprintf("%x", hash)
}

// writeConfig writes configuration to file
func (w *Watcher) writeConfig(config string) error {
	// Write to temporary file first
	tmpFile := w.cfg.ConfigFilePath + ".tmp"

	if err := os.WriteFile(tmpFile, []byte(config), 0644); err != nil {
		return fmt.Errorf("failed to write temp file: %w", err)
	}

	// Atomic rename
	if err := os.Rename(tmpFile, w.cfg.ConfigFilePath); err != nil {
		return fmt.Errorf("failed to rename config file: %w", err)
	}

	log.Printf("📝 Config written to %s", w.cfg.ConfigFilePath)

	// Touch reload signal file if it exists
	reloadSignal := "/tmp/traefik-reload-signal"
	if _, err := os.Stat(reloadSignal); err == nil {
		now := time.Now()
		if err := os.Chtimes(reloadSignal, now, now); err != nil {
			log.Printf("⚠️  Failed to touch reload signal: %v", err)
		} else {
			log.Println("🔄 Traefik reload signal triggered")
		}
	}

	return nil
}

