package main

import (
	"context"
	"crypto/md5"
	"crypto/sha256"
	"encoding/json"
	"fmt"
	"log"
	"os"
	"strings"
	"time"

	"github.com/lib/pq"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

const (
	apiServiceName      = "api-service"
	redirectServiceName = "redirect-service"
)

type challengeMiddleware struct {
	Name string
	Body string
}

// AppInfo holds application routing information
type AppInfo struct {
	Name          string
	Namespace     string
	Domain        string   // primary domain (app_public_settings.custom_domain)
	CustomDomains []string // all active custom domains
	Port          int
	SSLEnabled    bool
	Status        string
	ServiceIP     string
}

// reconcile is the main reconciliation loop
func (w *Watcher) reconcile() error {
	start := time.Now()

	// 1. Fetch apps from database
	appsFromDB, err := w.fetchAppsFromDB()
	if err != nil {
		return fmt.Errorf("failed to fetch apps from DB: %w", err)
	}

	log.Printf("📊 Found %d apps in database", len(appsFromDB))

	// 2. If using Kubernetes, enrich with k8s service info
	if w.k8sClient != nil {
		if err := w.enrichWithKubernetesInfo(appsFromDB); err != nil {
			log.Printf("⚠️  K8s enrichment failed: %v", err)
		}
	}

	// 3. Generate Traefik configuration
	config := w.generateTraefikConfig(appsFromDB)

	// 4. Calculate config hash
	configHash := w.calculateHash(config)

	// 5. Check if config changed
	if configHash == w.lastHash {
		log.Printf("✓ Config unchanged (hash: %s)", configHash[:8])
		return nil
	}

	// 6. Write config to file
	if err := w.writeConfig(config); err != nil {
		return fmt.Errorf("failed to write config: %w", err)
	}

	// 7. Update hash
	w.lastHash = configHash

	elapsed := time.Since(start)
	log.Printf("✅ Config updated successfully (hash: %s, elapsed: %v)", configHash[:8], elapsed)

	return nil
}

// fetchAppsFromDB queries database for deployed apps
func (w *Watcher) fetchAppsFromDB() ([]AppInfo, error) {
	query := `
		SELECT 
			d.app_name,
			COALESCE(d.port, 3000) as port,
			d.status,
			COALESCE(s.custom_domain, '') as custom_domain,
			COALESCE(s.ssl_enabled, false) as ssl_enabled,
			COALESCE(array_agg(cd.domain) FILTER (WHERE cd.domain IS NOT NULL AND cd.is_active = true), '{}') as custom_domains
		FROM app_deployments d
		LEFT JOIN app_public_settings s ON d.app_name = s.app_name
		LEFT JOIN app_custom_domains cd ON cd.app_name = d.app_name
		WHERE d.status = 'deployed'
		GROUP BY d.app_name, d.port, d.status, s.custom_domain, s.ssl_enabled
		ORDER BY d.app_name
	`

	rows, err := w.db.Query(query)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var apps []AppInfo
	for rows.Next() {
		var app AppInfo
		var customDomains []string
		if err := rows.Scan(&app.Name, &app.Port, &app.Status, &app.Domain, &app.SSLEnabled, pq.Array(&customDomains)); err != nil {
			log.Printf("⚠️  Failed to scan row: %v", err)
			continue
		}

		app.CustomDomains = dedupeDomains(append([]string{app.Domain}, customDomains...))

		// Set namespace for k8s mode
		if w.k8sClient != nil {
			app.Namespace = "citizen-app-" + app.Name
		}

		apps = append(apps, app)
	}

	return apps, rows.Err()
}

// enrichWithKubernetesInfo adds Kubernetes service information
func (w *Watcher) enrichWithKubernetesInfo(apps []AppInfo) error {
	for i := range apps {
		app := &apps[i]

		// Get service from Kubernetes
		svc, err := w.k8sClient.CoreV1().Services(app.Namespace).Get(
			context.TODO(),
			app.Name,
			metav1.GetOptions{},
		)

		if err != nil {
			log.Printf("⚠️  Service not found for %s: %v", app.Name, err)
			continue
		}

		// Update with actual service IP
		app.ServiceIP = svc.Spec.ClusterIP

		// Use service port if available
		if len(svc.Spec.Ports) > 0 {
			app.Port = int(svc.Spec.Ports[0].Port)
		}

		log.Printf("🔍 Enriched %s: IP=%s, Port=%d", app.Name, app.ServiceIP, app.Port)
	}

	return nil
}

// generateTraefikConfig generates Traefik dynamic configuration YAML
func (w *Watcher) generateTraefikConfig(apps []AppInfo) string {
	var sb strings.Builder

	sb.WriteString("# Traefik Dynamic Configuration\n")
	sb.WriteString("# Generated by Citizen Traefik Watcher v2\n")
	sb.WriteString(fmt.Sprintf("# Generated at: %s\n", time.Now().Format(time.RFC3339)))
	sb.WriteString("# DO NOT EDIT MANUALLY - This file is auto-generated\n\n")

	sb.WriteString("http:\n")
	sb.WriteString("  routers:\n")
	routersWritten := w.writeBaseRouters(&sb)
	for _, app := range apps {
		if w.writeAppRouters(&sb, app) {
			routersWritten = true
		}
	}
	challengeMiddlewares, challengeWritten := w.writeHTTPChallengeRouters(&sb)
	if challengeWritten {
		routersWritten = true
	}
	if !routersWritten {
		sb.WriteString("    {}\n")
	}

	// SSE transport with long timeout (10 minutes)
	sb.WriteString("  serversTransports:\n")
	sb.WriteString("    sse-transport:\n")
	sb.WriteString("      forwardingTimeouts:\n")
	sb.WriteString("        dialTimeout: 30s\n")
	sb.WriteString("        responseHeaderTimeout: 600s\n")
	sb.WriteString("        idleConnTimeout: 600s\n\n")

	sb.WriteString("  services:\n")
	servicesWritten := w.writeBaseServices(&sb)
	for _, app := range apps {
		if w.writeAppService(&sb, app) {
			servicesWritten = true
		}
	}
	if !servicesWritten {
		sb.WriteString("    {}\n")
	}

	sb.WriteString("  middlewares:\n")
	w.writeMiddlewares(&sb, challengeMiddlewares)

	w.writeTLSBlock(&sb)

	return sb.String()
}

// calculateHash calculates SHA256 hash of config
func (w *Watcher) calculateHash(config string) string {
	hash := sha256.Sum256([]byte(config))
	return fmt.Sprintf("%x", hash)
}

// writeConfig writes configuration to file
func (w *Watcher) writeConfig(config string) error {
	// Write to temporary file first
	tmpFile := w.cfg.ConfigFilePath + ".tmp"

	if err := os.WriteFile(tmpFile, []byte(config), 0644); err != nil {
		return fmt.Errorf("failed to write temp file: %w", err)
	}

	// Atomic rename
	if err := os.Rename(tmpFile, w.cfg.ConfigFilePath); err != nil {
		return fmt.Errorf("failed to rename config file: %w", err)
	}

	log.Printf("📝 Config written to %s", w.cfg.ConfigFilePath)

	// Touch reload signal file if it exists
	reloadSignal := "/tmp/traefik-reload-signal"
	if _, err := os.Stat(reloadSignal); err == nil {
		now := time.Now()
		if err := os.Chtimes(reloadSignal, now, now); err != nil {
			log.Printf("⚠️  Failed to touch reload signal: %v", err)
		} else {
			log.Println("🔄 Traefik reload signal triggered")
		}
	}

	return nil
}

func (w *Watcher) writeBaseRouters(sb *strings.Builder) bool {
	domain := strings.TrimSpace(w.cfg.PlatformDomain)
	if domain == "" {
		return false
	}

	safeDomain := escapeBackticks(domain)

	if w.cfg.EnableTLS {
		sb.WriteString("    main-http:\n")
		sb.WriteString(fmt.Sprintf("      rule: \"Host(`%s`)\"\n", safeDomain))
		sb.WriteString(fmt.Sprintf("      service: %s\n", apiServiceName))
		sb.WriteString("      entryPoints:\n        - web\n")
		sb.WriteString("      middlewares:\n        - https-redirect\n")
		sb.WriteString("      priority: 90\n\n")

		w.writePlatformSecureRoutes(sb, safeDomain)
	} else {
		sb.WriteString("    sso-http:\n")
		sb.WriteString(fmt.Sprintf("      rule: \"Host(`%s`) && PathPrefix(`/sso/`)\"\n", safeDomain))
		sb.WriteString(fmt.Sprintf("      service: %s\n", apiServiceName))
		sb.WriteString("      entryPoints:\n        - web\n")
		sb.WriteString("      middlewares:\n        - no-cache\n        - security-headers\n")
		sb.WriteString("      priority: 130\n\n")

		sb.WriteString("    auth-api-http:\n")
		sb.WriteString(fmt.Sprintf("      rule: \"Host(`%s`) && PathPrefix(`/api/v1/auth`)\"\n", safeDomain))
		sb.WriteString(fmt.Sprintf("      service: %s\n", apiServiceName))
		sb.WriteString("      entryPoints:\n        - web\n")
		sb.WriteString("      middlewares:\n        - no-cache\n        - security-headers\n")
		sb.WriteString("      priority: 120\n\n")

		// GitHub webhook - public endpoint (no auth required, validated via HMAC signature)
		sb.WriteString("    github-webhook-http:\n")
		sb.WriteString(fmt.Sprintf("      rule: \"Host(`%s`) && Path(`/api/v1/github/webhook`)\"\n", safeDomain))
		sb.WriteString(fmt.Sprintf("      service: %s\n", apiServiceName))
		sb.WriteString("      entryPoints:\n        - web\n")
		sb.WriteString("      middlewares:\n        - no-cache\n        - security-headers\n")
		sb.WriteString("      priority: 125\n\n")

		// GitHub OAuth/App callbacks - public endpoints (validated via state parameter)
		sb.WriteString("    github-callbacks-http:\n")
		sb.WriteString(fmt.Sprintf("      rule: \"Host(`%s`) && PathPrefix(`/api/v1/github/auth/callback`, `/api/v1/github/app/`)\"\n", safeDomain))
		sb.WriteString(fmt.Sprintf("      service: %s\n", apiServiceName))
		sb.WriteString("      entryPoints:\n        - web\n")
		sb.WriteString("      middlewares:\n        - no-cache\n        - security-headers\n")
		sb.WriteString("      priority: 118\n\n")

		sb.WriteString("    protected-api-http:\n")
		sb.WriteString(fmt.Sprintf("      rule: \"Host(`%s`) && PathPrefix(`/api`)\"\n", safeDomain))
		sb.WriteString(fmt.Sprintf("      service: %s\n", apiServiceName))
		sb.WriteString("      entryPoints:\n        - web\n")
		sb.WriteString("      middlewares:\n        - auth-api\n        - no-cache\n        - security-headers\n")
		sb.WriteString("      priority: 110\n\n")

		sb.WriteString("    main-root-http:\n")
		sb.WriteString(fmt.Sprintf("      rule: \"Host(`%s`)\"\n", safeDomain))
		sb.WriteString(fmt.Sprintf("      service: %s\n", apiServiceName))
		sb.WriteString("      entryPoints:\n        - web\n")
		sb.WriteString("      middlewares:\n        - auth-api\n        - no-cache\n        - security-headers\n")
		sb.WriteString("      priority: 100\n\n")
	}

	return true
}

func (w *Watcher) writePlatformSecureRoutes(sb *strings.Builder, safeDomain string) {

	sb.WriteString("    sso-https:\n")
	sb.WriteString(fmt.Sprintf("      rule: \"Host(`%s`) && PathPrefix(`/sso/`)\"\n", safeDomain))
	sb.WriteString(fmt.Sprintf("      service: %s\n", apiServiceName))
	sb.WriteString("      entryPoints:\n        - websecure\n")
	sb.WriteString("      middlewares:\n        - no-cache\n        - security-headers\n")
	sb.WriteString("      tls:\n        certResolver: letsencrypt\n")
	sb.WriteString("      priority: 130\n\n")

	sb.WriteString("    auth-api-https:\n")
	sb.WriteString(fmt.Sprintf("      rule: \"Host(`%s`) && PathPrefix(`/api/v1/auth`)\"\n", safeDomain))
	sb.WriteString(fmt.Sprintf("      service: %s\n", apiServiceName))
	sb.WriteString("      entryPoints:\n        - websecure\n")
	sb.WriteString("      middlewares:\n        - no-cache\n        - security-headers\n")
	sb.WriteString("      tls:\n        certResolver: letsencrypt\n")
	sb.WriteString("      priority: 120\n\n")

	// GitHub webhook - public endpoint (no auth required, validated via HMAC signature)
	sb.WriteString("    github-webhook-https:\n")
	sb.WriteString(fmt.Sprintf("      rule: \"Host(`%s`) && Path(`/api/v1/github/webhook`)\"\n", safeDomain))
	sb.WriteString(fmt.Sprintf("      service: %s\n", apiServiceName))
	sb.WriteString("      entryPoints:\n        - websecure\n")
	sb.WriteString("      middlewares:\n        - no-cache\n        - security-headers\n")
	sb.WriteString("      tls:\n        certResolver: letsencrypt\n")
	sb.WriteString("      priority: 125\n\n")

	// GitHub OAuth/App callbacks - public endpoints (validated via state parameter)
	sb.WriteString("    github-callbacks-https:\n")
	sb.WriteString(fmt.Sprintf("      rule: \"Host(`%s`) && PathPrefix(`/api/v1/github/auth/callback`, `/api/v1/github/app/`)\"\n", safeDomain))
	sb.WriteString(fmt.Sprintf("      service: %s\n", apiServiceName))
	sb.WriteString("      entryPoints:\n        - websecure\n")
	sb.WriteString("      middlewares:\n        - no-cache\n        - security-headers\n")
	sb.WriteString("      tls:\n        certResolver: letsencrypt\n")
	sb.WriteString("      priority: 118\n\n")

	sb.WriteString("    service-api-https:\n")
	sb.WriteString(fmt.Sprintf("      rule: \"Host(`%s`) && PathPrefix(`/api/v1/service`)\"\n", safeDomain))
	sb.WriteString(fmt.Sprintf("      service: %s\n", apiServiceName))
	sb.WriteString("      entryPoints:\n        - websecure\n")
	sb.WriteString("      middlewares:\n        - no-cache\n        - security-headers\n")
	sb.WriteString("      tls:\n        certResolver: letsencrypt\n")
	sb.WriteString("      priority: 115\n\n")

	// SSE endpoints with long timeout service
	sb.WriteString("    sse-api-https:\n")
	sb.WriteString(fmt.Sprintf("      rule: \"Host(`%s`) && PathPrefix(`/api/v1/sse/`)\"\n", safeDomain))
	sb.WriteString("      service: sse-api-service\n")
	sb.WriteString("      entryPoints:\n        - websecure\n")
	sb.WriteString("      middlewares:\n        - auth-api\n        - security-headers\n")
	sb.WriteString("      tls:\n        certResolver: letsencrypt\n")
	sb.WriteString("      priority: 135\n\n")

	sb.WriteString("    protected-api-https:\n")
	sb.WriteString(fmt.Sprintf("      rule: \"Host(`%s`) && PathPrefix(`/api`)\"\n", safeDomain))
	sb.WriteString(fmt.Sprintf("      service: %s\n", apiServiceName))
	sb.WriteString("      entryPoints:\n        - websecure\n")
	sb.WriteString("      middlewares:\n        - auth-api\n        - no-cache\n        - security-headers\n")
	sb.WriteString("      tls:\n        certResolver: letsencrypt\n")
	sb.WriteString("      priority: 110\n\n")

	sb.WriteString("    main-root-https:\n")
	sb.WriteString(fmt.Sprintf("      rule: \"Host(`%s`)\"\n", safeDomain))
	sb.WriteString(fmt.Sprintf("      service: %s\n", apiServiceName))
	sb.WriteString("      entryPoints:\n        - websecure\n")
	sb.WriteString("      middlewares:\n        - auth-api\n        - no-cache\n        - security-headers\n")
	sb.WriteString("      tls:\n        certResolver: letsencrypt\n")
	sb.WriteString("      priority: 100\n\n")
}

func (w *Watcher) writeAppRouters(sb *strings.Builder, app AppInfo) bool {
	serviceName := w.serviceName(app.Name)
	var wrote bool
	seen := map[string]bool{}

	if domain := strings.TrimSpace(w.cfg.PlatformDomain); domain != "" {
		host := fmt.Sprintf("%s.%s", slugify(app.Name), domain)
		if w.writeDomainRouters(sb, host, fmt.Sprintf("%s-subdomain", slugify(app.Name)), serviceName, w.cfg.EnableTLS) {
			wrote = true
		}
		seen[host] = true
	}

	// Primary custom domain first (kept for backward compatibility)
	if custom := strings.TrimSpace(app.Domain); custom != "" {
		if !seen[custom] && w.writeDomainRouters(sb, custom, fmt.Sprintf("%s-custom", slugify(app.Name)), serviceName, app.SSLEnabled || w.cfg.EnableTLS) {
			wrote = true
			seen[custom] = true
		}
	}

	// Additional custom domains
	for idx, host := range app.CustomDomains {
		host = strings.TrimSpace(host)
		if host == "" || seen[host] {
			continue
		}
		prefix := fmt.Sprintf("%s-custom-%d", slugify(app.Name), idx+1)
		if w.writeDomainRouters(sb, host, prefix, serviceName, app.SSLEnabled || w.cfg.EnableTLS) {
			wrote = true
			seen[host] = true
		}
	}

	return wrote
}

func (w *Watcher) writeDomainRouters(sb *strings.Builder, host, prefix, serviceName string, tlsEnabled bool) bool {
	host = strings.TrimSpace(host)
	if host == "" {
		return false
	}
	safeHost := escapeBackticks(host)
	prefix = slugify(prefix)
	if prefix == "" {
		prefix = "app"
	}

	ssoBase := fmt.Sprintf("%s-sso", prefix)
	appBase := fmt.Sprintf("%s-router", prefix)

	if tlsEnabled {
		sb.WriteString(fmt.Sprintf("    %s-http:\n", ssoBase))
		sb.WriteString(fmt.Sprintf("      rule: \"Host(`%s`) && PathPrefix(`/sso/`)\"\n", safeHost))
		sb.WriteString(fmt.Sprintf("      service: %s\n", apiServiceName))
		sb.WriteString("      entryPoints:\n        - web\n")
		sb.WriteString("      middlewares:\n        - redirect-to-https\n")
		sb.WriteString("      priority: 60\n\n")

		sb.WriteString(fmt.Sprintf("    %s-http:\n", appBase))
		sb.WriteString(fmt.Sprintf("      rule: \"Host(`%s`)\"\n", safeHost))
		sb.WriteString(fmt.Sprintf("      service: %s\n", serviceName))
		sb.WriteString("      entryPoints:\n        - web\n")
		sb.WriteString("      middlewares:\n        - redirect-to-https\n")
		sb.WriteString("      priority: 40\n\n")

		sb.WriteString(fmt.Sprintf("    %s-https:\n", ssoBase))
		sb.WriteString(fmt.Sprintf("      rule: \"Host(`%s`) && PathPrefix(`/sso/`)\"\n", safeHost))
		sb.WriteString(fmt.Sprintf("      service: %s\n", apiServiceName))
		sb.WriteString("      entryPoints:\n        - websecure\n")
		sb.WriteString("      middlewares:\n        - no-cache\n        - security-headers\n")
		sb.WriteString("      tls:\n        certResolver: letsencrypt\n")
		sb.WriteString("      priority: 120\n\n")

		sb.WriteString(fmt.Sprintf("    %s-https:\n", appBase))
		sb.WriteString(fmt.Sprintf("      rule: \"Host(`%s`)\"\n", safeHost))
		sb.WriteString(fmt.Sprintf("      service: %s\n", serviceName))
		sb.WriteString("      entryPoints:\n        - websecure\n")
		sb.WriteString("      middlewares:\n        - auth-api\n        - no-cache\n        - security-headers\n")
		sb.WriteString("      tls:\n        certResolver: letsencrypt\n")
		sb.WriteString("      priority: 50\n\n")
	} else {
		sb.WriteString(fmt.Sprintf("    %s:\n", ssoBase))
		sb.WriteString(fmt.Sprintf("      rule: \"Host(`%s`) && PathPrefix(`/sso/`)\"\n", safeHost))
		sb.WriteString(fmt.Sprintf("      service: %s\n", apiServiceName))
		sb.WriteString("      entryPoints:\n        - web\n")
		sb.WriteString("      middlewares:\n        - no-cache\n        - security-headers\n")
		sb.WriteString("      priority: 60\n\n")

		sb.WriteString(fmt.Sprintf("    %s:\n", appBase))
		sb.WriteString(fmt.Sprintf("      rule: \"Host(`%s`)\"\n", safeHost))
		sb.WriteString(fmt.Sprintf("      service: %s\n", serviceName))
		sb.WriteString("      entryPoints:\n        - web\n")
		sb.WriteString("      middlewares:\n        - auth-api\n        - no-cache\n        - security-headers\n")
		sb.WriteString("      priority: 50\n\n")
	}

	return true
}

func (w *Watcher) writeAppService(sb *strings.Builder, app AppInfo) bool {
	if strings.TrimSpace(w.cfg.PlatformDomain) == "" && strings.TrimSpace(app.Domain) == "" && len(app.CustomDomains) == 0 {
		return false
	}

	serviceName := w.serviceName(app.Name)
	sb.WriteString(fmt.Sprintf("    %s:\n", serviceName))
	sb.WriteString("      loadBalancer:\n")
	sb.WriteString("        servers:\n")
	if app.ServiceIP != "" {
		sb.WriteString(fmt.Sprintf("          - url: \"http://%s:%d\"\n", app.ServiceIP, app.Port))
	} else {
		sb.WriteString(fmt.Sprintf("          - url: \"http://%s:%d\"\n", app.Name, app.Port))
	}
	sb.WriteString("\n")
	return true
}

func (w *Watcher) serviceName(appName string) string {
	return fmt.Sprintf("citizen-%s-service", slugify(appName))
}

func (w *Watcher) writeBaseServices(sb *strings.Builder) bool {
	serviceURL := strings.TrimSpace(w.cfg.PlatformServiceURL)
	if serviceURL == "" {
		serviceURL = "http://citizen-platform-api:3000"
	}

	sb.WriteString(fmt.Sprintf("    %s:\n", apiServiceName))
	sb.WriteString("      loadBalancer:\n")
	sb.WriteString("        responseForwarding:\n")
	sb.WriteString("          flushInterval: 1ms\n")
	sb.WriteString("        servers:\n")
	sb.WriteString(fmt.Sprintf("          - url: \"%s\"\n\n", serviceURL))

	// SSE service with long timeout transport
	sb.WriteString("    sse-api-service:\n")
	sb.WriteString("      loadBalancer:\n")
	sb.WriteString("        serversTransport: sse-transport\n")
	sb.WriteString("        responseForwarding:\n")
	sb.WriteString("          flushInterval: 1ms\n")
	sb.WriteString("        servers:\n")
	sb.WriteString(fmt.Sprintf("          - url: \"%s\"\n\n", serviceURL))

	sb.WriteString(fmt.Sprintf("    %s:\n", redirectServiceName))
	sb.WriteString("      loadBalancer:\n")
	sb.WriteString("        servers:\n")
	sb.WriteString("          - url: \"http://127.0.0.1:80\"\n\n")

	return true
}

func (w *Watcher) writeMiddlewares(sb *strings.Builder, challengeMW []challengeMiddleware) {
	sb.WriteString("    https-redirect:\n")
	sb.WriteString("      redirectScheme:\n")
	sb.WriteString("        scheme: https\n")
	sb.WriteString("        permanent: true\n\n")

	authURL := strings.TrimRight(strings.TrimSpace(w.cfg.PlatformServiceURL), "/")
	if authURL == "" {
		authURL = "http://citizen-platform-api:3000"
	}
	authURL = authURL + "/api/v1/auth/validate"

	sb.WriteString("    auth-api:\n")
	sb.WriteString("      forwardAuth:\n")
	sb.WriteString(fmt.Sprintf("        address: \"%s\"\n", authURL))
	sb.WriteString("        trustForwardHeader: true\n")
	sb.WriteString("        authRequestHeaders:\n")
	sb.WriteString("          - \"Cookie\"\n")
	sb.WriteString("          - \"Authorization\"\n")
	sb.WriteString("        authResponseHeaders:\n")
	sb.WriteString("          - \"X-Auth-User-ID\"\n")
	sb.WriteString("          - \"X-Auth-Email\"\n")
	sb.WriteString("          - \"X-Auth-Name\"\n")
	sb.WriteString("          - \"X-Auth-Organization-ID\"\n\n")

	sb.WriteString("    no-cache:\n")
	sb.WriteString("      headers:\n")
	sb.WriteString("        customResponseHeaders:\n")
	sb.WriteString("          Cache-Control: \"no-store, no-cache, must-revalidate, private\"\n")
	sb.WriteString("          Pragma: \"no-cache\"\n")
	sb.WriteString("          Expires: \"0\"\n\n")

	sb.WriteString("    security-headers:\n")
	sb.WriteString("      headers:\n")
	sb.WriteString("        customResponseHeaders:\n")
	sb.WriteString("          X-Content-Type-Options: \"nosniff\"\n")
	sb.WriteString("          X-Frame-Options: \"DENY\"\n")
	sb.WriteString("          X-XSS-Protection: \"1; mode=block\"\n")
	sb.WriteString("          Referrer-Policy: \"strict-origin-when-cross-origin\"\n")
	sb.WriteString("        contentTypeNosniff: true\n")
	sb.WriteString("        frameDeny: true\n")
	sb.WriteString("        browserXssFilter: true\n\n")

	for _, mw := range challengeMW {
		sb.WriteString(fmt.Sprintf("    %s:\n", mw.Name))
		sb.WriteString("      plugin:\n")
		sb.WriteString("        customresponse:\n")
		sb.WriteString("          statusCode: 200\n")
		sb.WriteString("          contentType: text/plain\n")
		sb.WriteString(fmt.Sprintf("          body: \"%s\"\n", yamlEscape(mw.Body)))
		sb.WriteString("          allowedMethods:\n")
		sb.WriteString("            - GET\n")
		sb.WriteString("            - HEAD\n\n")
	}
}

func dedupeDomains(domains []string) []string {
	seen := make(map[string]struct{})
	out := make([]string, 0, len(domains))
	for _, d := range domains {
		d = strings.TrimSpace(d)
		if d == "" {
			continue
		}
		if _, ok := seen[d]; ok {
			continue
		}
		seen[d] = struct{}{}
		out = append(out, d)
	}
	return out
}

func (w *Watcher) writeTLSBlock(sb *strings.Builder) {
	sb.WriteString("\ntls:\n")
	sb.WriteString("  options:\n")
	sb.WriteString("    default:\n")
	sb.WriteString("      minVersion: VersionTLS12\n")
	sb.WriteString("      cipherSuites:\n")
	sb.WriteString("        - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256\n")
	sb.WriteString("        - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384\n")
	sb.WriteString("        - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305\n")
	sb.WriteString("        - TLS_AES_128_GCM_SHA256\n")
	sb.WriteString("        - TLS_AES_256_GCM_SHA384\n")
	sb.WriteString("        - TLS_CHACHA20_POLY1305_SHA256\n")
}

func (w *Watcher) writeHTTPChallengeRouters(sb *strings.Builder) ([]challengeMiddleware, bool) {
	path := strings.TrimSpace(w.cfg.HTTPChallengeFile)
	if path == "" {
		return nil, false
	}

	data, err := os.ReadFile(path)
	if err != nil || len(strings.TrimSpace(string(data))) == 0 {
		return nil, false
	}

	var entries []struct {
		Host string `json:"host"`
		Path string `json:"path"`
		Body string `json:"body"`
	}
	if err := json.Unmarshal(data, &entries); err != nil {
		log.Printf("⚠️  Failed to parse HTTP challenge file %s: %v", path, err)
		return nil, false
	}

	seen := make(map[string]bool)
	var challengeMW []challengeMiddleware
	wrote := false

	for _, entry := range entries {
		host := strings.TrimSpace(entry.Host)
		pathValue := strings.TrimSpace(entry.Path)
		body := entry.Body
		if host == "" || pathValue == "" || strings.TrimSpace(body) == "" {
			continue
		}
		key := host + "|" + pathValue
		if seen[key] {
			continue
		}
		seen[key] = true

		slug := slugify(host)
		hash := md5.Sum([]byte(host + pathValue))
		routerName := fmt.Sprintf("cf-http-challenge-%s-%x", slug, hash[:4])
		middlewareName := routerName + "-body"

		sb.WriteString(fmt.Sprintf("    %s:\n", routerName))
		sb.WriteString(fmt.Sprintf("      rule: \"Host(`%s`) && Path(`%s`)\"\n", escapeBackticks(host), escapeBackticks(pathValue)))
		sb.WriteString("      entryPoints:\n        - web\n")
		sb.WriteString("      service: noop@internal\n")
		sb.WriteString("      middlewares:\n")
		sb.WriteString(fmt.Sprintf("        - \"%s\"\n", middlewareName))
		sb.WriteString("      priority: 2000\n\n")

		challengeMW = append(challengeMW, challengeMiddleware{
			Name: middlewareName,
			Body: body,
		})
		wrote = true
	}

	return challengeMW, wrote
}

func escapeBackticks(value string) string {
	return strings.ReplaceAll(value, "`", "\\`")
}

func yamlEscape(value string) string {
	value = strings.ReplaceAll(value, `\`, `\\`)
	value = strings.ReplaceAll(value, `"`, `\"`)
	value = strings.ReplaceAll(value, "\n", `\n`)
	value = strings.ReplaceAll(value, "\r", `\r`)
	return value
}

func slugify(value string) string {
	value = strings.ToLower(strings.TrimSpace(value))
	var b strings.Builder
	prevDash := false
	for _, r := range value {
		switch {
		case r >= 'a' && r <= 'z':
			b.WriteRune(r)
			prevDash = false
		case r >= '0' && r <= '9':
			b.WriteRune(r)
			prevDash = false
		case r == '-' || r == '_' || r == '.' || r == ' ':
			if !prevDash {
				b.WriteRune('-')
				prevDash = true
			}
		default:
			// skip
		}
	}
	slug := strings.Trim(b.String(), "-")
	if slug == "" {
		slug = "app"
	}
	return slug
}
