root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/main ."
  bin = "tmp/main"
  full_bin = "APP_ENV=dev APP_USER=air ./tmp/main"
  include_ext = ["go", "tpl", "tmpl", "html"]
  exclude_dir = ["assets", "tmp", "vendor"]
  include_dir = []
  exclude_file = []
  log = "air-build-errors.log"
  delay = 1000 # ms
  stop_on_error = true
  send_interrupt = false
  kill_delay = 500 # ms

[log]
  time = true

[color]
  main = "yellow"
  watcher = "cyan"
  build = "blue"
  runner = "green"

[misc]
  clean_on_exit = true
